USE [DMA-CSD-S212_10407512]
GO

declare @date DATE = '2022-11-11';
declare @dt DATETIME = @date;

INSERT INTO [Person] VALUES ('Joe', 'Banana', 'joe@joe.com', '12345678', 'Guest', null)
INSERT INTO [Person] VALUES ('Børge', 'Børgemand', 'Børgemand@hotmail.com', '87654321', 'Employee', 'BBM') 
INSERT INTO [Product] VALUES ('Apple juice', 'Kings', 5, 'Sweet and Natural', 50, '010101')
INSERT INTO [Order] VALUES (1, @dt, 0, 0, 1, 'joe@joe.com', 'BBM')
INSERT INTO [Orderline] VALUES (@@IDENTITY, 5, 25, 010101) --@@IDENTITY contains the last identity value that is generated by a statement, INSERT, SELECT, or bulk